sudo: required
services:
  - docker
before_install:
  - docker build -t srishty01/docker-react -f Dockerfile.dev .
Script:
  - docker run srishty01/docker-react npm run test -- --coverage --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-776745732933"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
