sudo: required
services:
  - docker
before_install:
  - docker build -t srishty01/docker-react -f Dockerfile.dev .
Script:
  - docker run srishty01/docker-react npm run test -- --coverage --watchAll=false
